sprintstart:
  internal-event-secret: ${SPRINTSTART_KEYCLOAK_SHARED_SECRET:test-secret}
  ai:
    base-url: ${SPRINTSTART_AI_BASE_URL:http://host.docker.internal:8000}
  github:
    cache-path: ${REPO_CACHE_PATH:${java.io.tmpdir}/repos}
    base-url: "https://api.github.com/graphql"
    repo-base-url: "https://api.github.com/repos"
    token: ${GITHUB_PAT}
    cron: "0 2 * * 1" # Every Monday night at 2:00 am
  crypto:
    master-key: ${CRYPTO_MASTER_KEY}
    salt: ${CRYPTO_SALT}

spring:
  config:
    import: optional:file:./run.local.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update # create-drop
    show-sql: true
  mvc:
    async:
      request-timeout: 600000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/auth/realms/sprintstart}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8081/auth/realms/sprintstart/protocol/openid-connect/certs}

app:
  upload:
    directory: uploads
    max-file-size-bytes: 10485760
