spring:
  config:
    import: optional:file:./run.local.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

app:
  upload:
    directory: uploads
    max-file-size-bytes: 10485760