package com.sprintstart.sprintstartbackend.onboarding.blueprint.factory

import com.sprintstart.sprintstartbackend.onboarding.blueprint.external.enums.BlueprintPhaseType
import com.sprintstart.sprintstartbackend.onboarding.blueprint.external.enums.RequirementType
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintCheckOption
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintCheckQuestion
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintPath
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintPhase
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintResource
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintStep
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintTask
import com.sprintstart.sprintstartbackend.onboarding.external.enums.CheckQuestionType
import com.sprintstart.sprintstartbackend.onboarding.external.enums.GenerationStatus
import com.sprintstart.sprintstartbackend.onboarding.external.enums.StepStatus
import com.sprintstart.sprintstartbackend.onboarding.external.enums.StepType
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingPath
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingPhase
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingResource
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingStep
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingSubGraphNode
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingTask
import com.sprintstart.sprintstartbackend.onboarding.model.entity.PhaseCheckOption
import com.sprintstart.sprintstartbackend.onboarding.model.entity.PhaseCheckQuestion
import org.springframework.stereotype.Component
import java.util.UUID

/** AI-generated content for one `AI_ENHANCED` blueprint phase, filled at personalization time. */
data class GeneratedPhaseContent(
    val steps: List<GeneratedStep> = emptyList(),
    val checkQuestions: List<GeneratedQuestion> = emptyList(),
)

/**
 * AI-generated step content as returned by the phase-assembly endpoint.
 *
 * [key] and [blockedBy] carry the optional dependency edges the model drew
 * between the assembled items: [blockedBy] holds the keys of steps/questions
 * that must be completed first. Keys are scoped to one assembled phase; a key
 * that resolves to nothing (unknown, self, or an item grounding dropped) is
 * ignored when the edges are wired onto the onboarding phase.
 */
data class GeneratedStep(
    val key: String = "",
    val title: String,
    val description: String = "",
    val tasks: List<GeneratedTask> = emptyList(),
    val resources: List<GeneratedResource> = emptyList(),
    val estimatedMinutes: Int? = null,
    val expectedOutcome: String = "",
    val blockedBy: List<String> = emptyList(),
)

data class GeneratedTask(
    val title: String,
    val description: String = "",
)

data class GeneratedResource(
    val title: String,
    val url: String,
)

/**
 * AI-generated knowledge-check question as returned by the phase-assembly endpoint.
 *
 * [key] and [blockedBy] mirror [GeneratedStep]: optional dependency edges,
 * resolved by key against the phase's assembled items.
 */
data class GeneratedQuestion(
    val key: String = "",
    val type: CheckQuestionType,
    val question: String,
    val explanation: String? = null,
    val correctAnswer: String? = null,
    val options: List<GeneratedOption> = emptyList(),
    val blockedBy: List<String> = emptyList(),
)

data class GeneratedOption(
    val label: String,
    val correct: Boolean = false,
)

/** Whether the phase's role/skill requirements are satisfied by the user profile. */
fun BlueprintPhase.isIncludedFor(projectRoleIds: Set<UUID>, skillIds: Set<UUID>): Boolean =
    requirements.all { requirement ->
        when (requirement.type) {
            RequirementType.PROJECT_ROLE -> requirement.referenceId in projectRoleIds
            RequirementType.SKILL -> requirement.referenceId in skillIds
        }
    }

/**
 * Creates a user-owned onboarding path from a fully authored blueprint path.
 *
 * The conversion copies content and graph layout into a new aggregate. Dependency
 * edges are rebuilt against the copied entities, keeping blueprint and onboarding
 * persistence ownership separate. Content generated by the AI service for
 * `AI_ENHANCED` phases (keyed by blueprint phase id) is merged in on top of the
 * authored content, so a prompt-only phase is filled with the assembled steps
 * and knowledge check while an [OnboardingPathFromBlueprintFactory] path keeps
 * the blueprint itself untouched.
 */
@Component
class OnboardingPathFromBlueprintFactory {
    /**
     * Deep-copies [blueprintPath] for [userId].
     *
     * @param blueprintPath The source blueprint whose complete graph is copied.
     * @param userId The user who owns the resulting onboarding path.
     * @param generatedContentByBlueprintPhaseId AI-assembled content for `AI_ENHANCED` phases,
     *   keyed by source blueprint phase id.
     * @return A new, unsaved onboarding path aggregate.
     */
    fun createFrom(
        blueprintPath: BlueprintPath,
        userId: UUID,
        projectRoleIds: Set<UUID> = emptySet(),
        skillIds: Set<UUID> = emptySet(),
        generatedContentByBlueprintPhaseId: Map<UUID, GeneratedPhaseContent> = emptyMap(),
        generationStatusByBlueprintPhaseId: Map<UUID, GenerationStatus> = emptyMap(),
    ): OnboardingPath {
        val onboardingPath = OnboardingPath(
            userId = userId,
            blueprintId = blueprintPath.id,
        )
        val phasesByBlueprintId = mutableMapOf<UUID, OnboardingPhase>()
        val nodesByBlueprintId = mutableMapOf<UUID, OnboardingSubGraphNode>()
        val includedPhases = blueprintPath.blueprintPhases.filter { phase ->
            phase.isIncludedFor(projectRoleIds, skillIds)
        }

        includedPhases
            .sortedBy { it.position }
            .map {
                it.copyTo(
                    onboardingPath = onboardingPath,
                    nodesByBlueprintId = nodesByBlueprintId,
                    generated = generatedContentByBlueprintPhaseId[it.id],
                    generationStatus = generationStatusByBlueprintPhaseId[it.id],
                )
            }.forEach { copied ->
                onboardingPath.phases += copied.entity
                phasesByBlueprintId[copied.sourceBlueprintId] = copied.entity
            }

        wirePhaseBlockers(includedPhases, phasesByBlueprintId)

        includedPhases
            .flatMap { it.blueprintSteps + it.blueprintCheckQuestions }
            .forEach { blueprintNode ->
                val onboardingNode = nodesByBlueprintId.getValue(blueprintNode.id)
                blueprintNode.blockedBy.forEach { blocker ->
                    nodesByBlueprintId[blocker.id]?.let(onboardingNode.blockedBy::add)
                }
            }

        return onboardingPath
    }

    private fun BlueprintPhase.copyTo(
        onboardingPath: OnboardingPath,
        nodesByBlueprintId: MutableMap<UUID, OnboardingSubGraphNode>,
        generated: GeneratedPhaseContent? = null,
        generationStatus: GenerationStatus? = null,
    ): CopiedPhase {
        val resolvedGenerationStatus = generationStatus ?: when {
            type != BlueprintPhaseType.AI_ENHANCED -> GenerationStatus.NOT_APPLICABLE
            generated == null || generated.isEmpty() -> GenerationStatus.EMPTY
            else -> GenerationStatus.GENERATED
        }
        val onboardingPhase = OnboardingPhase(
            path = onboardingPath,
            position = position,
            title = title,
            description = description.orEmpty(),
            generationStatus = resolvedGenerationStatus,
            graphX = graphX,
            graphY = graphY,
        )

        blueprintSteps
            .sortedBy { it.position }
            .map { it.copyTo(onboardingPhase) }
            .forEach { copied ->
                onboardingPhase.steps += copied.entity
                nodesByBlueprintId[copied.sourceBlueprintId] = copied.entity
            }

        blueprintCheckQuestions
            .sortedBy { it.position }
            .map { it.copyTo(onboardingPhase) }
            .forEach { copied ->
                onboardingPhase.checkQuestions += copied.entity
                nodesByBlueprintId[copied.sourceBlueprintId] = copied.entity
            }

        if (generated != null) {
            generated.copyInto(onboardingPhase)
        }

        return CopiedPhase(id, onboardingPhase)
    }

    private fun GeneratedPhaseContent.isEmpty(): Boolean = steps.isEmpty() && checkQuestions.isEmpty()

    private fun wirePhaseBlockers(
        includedPhases: List<BlueprintPhase>,
        phasesByBlueprintId: Map<UUID, OnboardingPhase>,
    ) {
        fun visibleBlockers(
            blueprintPhase: BlueprintPhase,
            visiting: MutableSet<UUID>,
        ): Set<OnboardingPhase> {
            val copied = phasesByBlueprintId[blueprintPhase.id] ?: return emptySet()
            if (!copied.generationStatus.isHiddenFromUser()) return setOf(copied)
            if (!visiting.add(blueprintPhase.id)) return emptySet()
            val inherited = blueprintPhase.blockedBy
                .flatMap { blocker -> visibleBlockers(blocker, visiting) }
                .toSet()
            visiting.remove(blueprintPhase.id)
            return inherited
        }

        includedPhases.forEach { blueprintPhase ->
            val onboardingPhase = phasesByBlueprintId.getValue(blueprintPhase.id)
            if (onboardingPhase.generationStatus.isHiddenFromUser()) {
                blueprintPhase.blockedBy
                    .mapNotNull { blocker -> phasesByBlueprintId[blocker.id] }
                    .forEach(onboardingPhase.blockedBy::add)
            } else {
                blueprintPhase.blockedBy
                    .flatMap { blocker -> visibleBlockers(blocker, mutableSetOf()) }
                    .forEach(onboardingPhase.blockedBy::add)
            }
        }
    }

    private fun GeneratedPhaseContent.copyInto(onboardingPhase: OnboardingPhase) {
        val nodesByKey = mutableMapOf<String, OnboardingSubGraphNode>()
        val nodes = mutableListOf<OnboardingSubGraphNode>()
        val nodeEdges = mutableListOf<List<String>>()

        var stepPosition = onboardingPhase.steps.maxOfOrNull { it.position }?.let { it + 1 } ?: 0
        for (step in steps) {
            val onboardingStep = OnboardingStep(
                phase = onboardingPhase,
                position = stepPosition,
                title = step.title,
                description = step.description,
                type = StepType.TASK,
                aiAssisted = true,
                estimatedMinutes = step.estimatedMinutes ?: 0,
                tasks = mutableListOf(),
                resources = mutableListOf(),
                expectedOutcome = step.expectedOutcome,
                status = StepStatus.WAITING,
            )
            step.tasks.forEachIndexed { index, task ->
                onboardingStep.tasks += OnboardingTask(
                    step = onboardingStep,
                    position = index,
                    title = task.title,
                    description = task.description,
                )
            }
            step.resources.forEach { resource ->
                onboardingStep.resources += OnboardingResource(
                    step = onboardingStep,
                    title = resource.title,
                    description = "",
                    url = resource.url,
                )
            }
            onboardingPhase.steps += onboardingStep
            registerNode(step.key, onboardingStep, nodesByKey, nodes, nodeEdges, step.blockedBy)
            stepPosition += 1
        }

        var questionPosition =
            onboardingPhase.checkQuestions.maxOfOrNull { it.position }?.let { it + 1 } ?: 0
        for (question in checkQuestions) {
            val onboardingQuestion = PhaseCheckQuestion(
                phase = onboardingPhase,
                position = questionPosition,
                type = question.type,
                question = question.question,
                explanation = question.explanation,
                correctAnswer = question.correctAnswer,
                options = mutableListOf(),
            )
            question.options.forEachIndexed { index, option ->
                onboardingQuestion.options += PhaseCheckOption(
                    question = onboardingQuestion,
                    position = index,
                    label = option.label,
                    correct = option.correct,
                )
            }
            onboardingPhase.checkQuestions += onboardingQuestion
            registerNode(question.key, onboardingQuestion, nodesByKey, nodes, nodeEdges, question.blockedBy)
            questionPosition += 1
        }

        // Edges are wired after every node exists so a reference may point at a
        // later item; a key that resolves to nothing or to the node itself is
        // dropped rather than left dangling.
        nodes.forEachIndexed { index, node ->
            for (blockerKey in nodeEdges[index]) {
                nodesByKey[blockerKey]?.let { blocker ->
                    if (blocker != node) {
                        node.blockedBy += blocker
                    }
                }
            }
        }
    }

    private fun registerNode(
        key: String,
        node: OnboardingSubGraphNode,
        nodesByKey: MutableMap<String, OnboardingSubGraphNode>,
        nodes: MutableList<OnboardingSubGraphNode>,
        nodeEdges: MutableList<List<String>>,
        blockedBy: List<String>,
    ) {
        nodes += node
        nodeEdges += blockedBy
        if (key.isNotBlank() && key !in nodesByKey) {
            nodesByKey[key] = node
        }
    }

    private fun BlueprintStep.copyTo(onboardingPhase: OnboardingPhase): CopiedNode<OnboardingStep> {
        val onboardingStep = OnboardingStep(
            phase = onboardingPhase,
            position = position,
            title = title,
            description = description,
            type = type,
            aiAssisted = aiAssisted,
            estimatedMinutes = estimatedMinutes,
            expectedOutcome = expectedOutcome,
            status = StepStatus.WAITING,
            graphX = graphX,
            graphY = graphY,
        )

        blueprintTasks
            .sortedBy { it.position }
            .map { it.copyTo(onboardingStep) }
            .forEach(onboardingStep.tasks::add)
        blueprintResources
            .map { it.copyTo(onboardingStep) }
            .forEach(onboardingStep.resources::add)

        return CopiedNode(id, onboardingStep)
    }

    private fun BlueprintCheckQuestion.copyTo(
        onboardingPhase: OnboardingPhase,
    ): CopiedNode<PhaseCheckQuestion> {
        val onboardingQuestion = PhaseCheckQuestion(
            phase = onboardingPhase,
            title = title,
            position = position,
            type = type,
            question = question,
            explanation = explanation,
            correctAnswer = correctAnswer,
            graphX = graphX,
            graphY = graphY,
        )

        blueprintCheckOptions
            .sortedBy { it.position }
            .map { it.copyTo(onboardingQuestion) }
            .forEach(onboardingQuestion.options::add)

        return CopiedNode(id, onboardingQuestion)
    }

    private fun BlueprintTask.copyTo(onboardingStep: OnboardingStep): OnboardingTask {
        return OnboardingTask(
            step = onboardingStep,
            position = position,
            title = title,
            description = description,
        )
    }

    private fun BlueprintResource.copyTo(onboardingStep: OnboardingStep): OnboardingResource {
        return OnboardingResource(
            step = onboardingStep,
            title = title,
            description = description,
            url = url,
        )
    }

    private fun BlueprintCheckOption.copyTo(onboardingQuestion: PhaseCheckQuestion): PhaseCheckOption {
        return PhaseCheckOption(
            question = onboardingQuestion,
            position = position,
            label = label,
            correct = correct,
        )
    }

    private data class CopiedPhase(
        val sourceBlueprintId: UUID,
        val entity: OnboardingPhase,
    )

    private data class CopiedNode<T : OnboardingSubGraphNode>(
        val sourceBlueprintId: UUID,
        val entity: T,
    )
}
