package com.sprintstart.sprintstartbackend.onboarding.blueprint.factory

import com.sprintstart.sprintstartbackend.onboarding.blueprint.external.enums.RequirementType
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintCheckOption
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintCheckQuestion
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintPath
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintPhase
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintResource
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintStep
import com.sprintstart.sprintstartbackend.onboarding.blueprint.model.entity.BlueprintTask
import com.sprintstart.sprintstartbackend.onboarding.external.enums.CheckQuestionType
import com.sprintstart.sprintstartbackend.onboarding.external.enums.StepStatus
import com.sprintstart.sprintstartbackend.onboarding.external.enums.StepType
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingPath
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingPhase
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingResource
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingStep
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingSubGraphNode
import com.sprintstart.sprintstartbackend.onboarding.model.entity.OnboardingTask
import com.sprintstart.sprintstartbackend.onboarding.model.entity.PhaseCheckOption
import com.sprintstart.sprintstartbackend.onboarding.model.entity.PhaseCheckQuestion
import org.springframework.stereotype.Component
import java.util.UUID

/** AI-generated content for one `AI_ENHANCED` blueprint phase, filled at personalization time. */
data class GeneratedPhaseContent(
    val steps: List<GeneratedStep> = emptyList(),
    val checkQuestions: List<GeneratedQuestion> = emptyList(),
)

/** AI-generated step content as returned by the phase-assembly endpoint. */
data class GeneratedStep(
    val title: String,
    val description: String = "",
    val tasks: List<GeneratedTask> = emptyList(),
    val resources: List<GeneratedResource> = emptyList(),
    val estimatedMinutes: Int? = null,
    val expectedOutcome: String = "",
)

data class GeneratedTask(
    val title: String,
    val description: String = "",
)

data class GeneratedResource(
    val title: String,
    val url: String,
)

/** AI-generated knowledge-check question as returned by the phase-assembly endpoint. */
data class GeneratedQuestion(
    val type: CheckQuestionType,
    val question: String,
    val explanation: String? = null,
    val correctAnswer: String? = null,
    val options: List<GeneratedOption> = emptyList(),
)

data class GeneratedOption(
    val label: String,
    val correct: Boolean = false,
)

/** Whether the phase's role/skill requirements are satisfied by the user profile. */
fun BlueprintPhase.isIncludedFor(projectRoleIds: Set<UUID>, skillIds: Set<UUID>): Boolean =
    requirements.all { requirement ->
        when (requirement.type) {
            RequirementType.PROJECT_ROLE -> requirement.referenceId in projectRoleIds
            RequirementType.SKILL -> requirement.referenceId in skillIds
        }
    }

/**
 * Creates a user-owned onboarding path from a fully authored blueprint path.
 *
 * The conversion copies content and graph layout into a new aggregate. Dependency
 * edges are rebuilt against the copied entities, keeping blueprint and onboarding
 * persistence ownership separate. Content generated by the AI service for
 * `AI_ENHANCED` phases (keyed by blueprint phase id) is merged in on top of the
 * authored content, so a prompt-only phase is filled with the assembled steps
 * and knowledge check while an [OnboardingPathFromBlueprintFactory] path keeps
 * the blueprint itself untouched.
 */
@Component
class OnboardingPathFromBlueprintFactory {
    /**
     * Deep-copies [blueprintPath] for [userId].
     *
     * @param blueprintPath The source blueprint whose complete graph is copied.
     * @param userId The user who owns the resulting onboarding path.
     * @param generatedContentByBlueprintPhaseId AI-assembled content for `AI_ENHANCED` phases,
     *   keyed by source blueprint phase id.
     * @return A new, unsaved onboarding path aggregate.
     */
    fun createFrom(
        blueprintPath: BlueprintPath,
        userId: UUID,
        projectRoleIds: Set<UUID> = emptySet(),
        skillIds: Set<UUID> = emptySet(),
        generatedContentByBlueprintPhaseId: Map<UUID, GeneratedPhaseContent> = emptyMap(),
    ): OnboardingPath {
        val onboardingPath = OnboardingPath(
            userId = userId,
            blueprintId = blueprintPath.id,
        )
        val phasesByBlueprintId = mutableMapOf<UUID, OnboardingPhase>()
        val nodesByBlueprintId = mutableMapOf<UUID, OnboardingSubGraphNode>()
        val includedPhases = blueprintPath.blueprintPhases.filter { phase ->
            phase.isIncludedFor(projectRoleIds, skillIds)
        }

        includedPhases
            .sortedBy { it.position }
            .map { it.copyTo(onboardingPath, nodesByBlueprintId, generatedContentByBlueprintPhaseId[it.id]) }
            .forEach { copied ->
                onboardingPath.phases += copied.entity
                phasesByBlueprintId[copied.sourceBlueprintId] = copied.entity
            }

        includedPhases.forEach { blueprintPhase ->
            val onboardingPhase = phasesByBlueprintId.getValue(blueprintPhase.id)
            blueprintPhase.blockedBy.forEach { blocker ->
                phasesByBlueprintId[blocker.id]?.let(onboardingPhase.blockedBy::add)
            }
        }

        includedPhases
            .flatMap { it.blueprintSteps + it.blueprintCheckQuestions }
            .forEach { blueprintNode ->
                val onboardingNode = nodesByBlueprintId.getValue(blueprintNode.id)
                blueprintNode.blockedBy.forEach { blocker ->
                    nodesByBlueprintId[blocker.id]?.let(onboardingNode.blockedBy::add)
                }
            }

        return onboardingPath
    }

    private fun BlueprintPhase.copyTo(
        onboardingPath: OnboardingPath,
        nodesByBlueprintId: MutableMap<UUID, OnboardingSubGraphNode>,
        generated: GeneratedPhaseContent? = null,
    ): CopiedPhase {
        val onboardingPhase = OnboardingPhase(
            path = onboardingPath,
            position = position,
            title = title,
            description = description.orEmpty(),
            graphX = graphX,
            graphY = graphY,
        )

        blueprintSteps
            .sortedBy { it.position }
            .map { it.copyTo(onboardingPhase) }
            .forEach { copied ->
                onboardingPhase.steps += copied.entity
                nodesByBlueprintId[copied.sourceBlueprintId] = copied.entity
            }

        blueprintCheckQuestions
            .sortedBy { it.position }
            .map { it.copyTo(onboardingPhase) }
            .forEach { copied ->
                onboardingPhase.checkQuestions += copied.entity
                nodesByBlueprintId[copied.sourceBlueprintId] = copied.entity
            }

        if (generated != null) {
            generated.copyInto(onboardingPhase)
        }

        return CopiedPhase(id, onboardingPhase)
    }

    private fun GeneratedPhaseContent.copyInto(onboardingPhase: OnboardingPhase) {
        var stepPosition = onboardingPhase.steps.maxOfOrNull { it.position }?.let { it + 1 } ?: 0
        for (step in steps) {
            val onboardingStep = OnboardingStep(
                phase = onboardingPhase,
                position = stepPosition,
                title = step.title,
                description = step.description,
                type = StepType.TASK,
                aiAssisted = true,
                estimatedMinutes = step.estimatedMinutes ?: 0,
                tasks = mutableListOf(),
                resources = mutableListOf(),
                expectedOutcome = step.expectedOutcome,
                status = StepStatus.WAITING,
            )
            step.tasks.forEachIndexed { index, task ->
                onboardingStep.tasks += OnboardingTask(
                    step = onboardingStep,
                    position = index,
                    title = task.title,
                    description = task.description,
                )
            }
            step.resources.forEach { resource ->
                onboardingStep.resources += OnboardingResource(
                    step = onboardingStep,
                    title = resource.title,
                    description = "",
                    url = resource.url,
                )
            }
            onboardingPhase.steps += onboardingStep
            stepPosition += 1
        }

        var questionPosition =
            onboardingPhase.checkQuestions.maxOfOrNull { it.position }?.let { it + 1 } ?: 0
        for (question in checkQuestions) {
            val onboardingQuestion = PhaseCheckQuestion(
                phase = onboardingPhase,
                position = questionPosition,
                type = question.type,
                question = question.question,
                explanation = question.explanation,
                correctAnswer = question.correctAnswer,
                options = mutableListOf(),
            )
            question.options.forEachIndexed { index, option ->
                onboardingQuestion.options += PhaseCheckOption(
                    question = onboardingQuestion,
                    position = index,
                    label = option.label,
                    correct = option.correct,
                )
            }
            onboardingPhase.checkQuestions += onboardingQuestion
            questionPosition += 1
        }
    }

    private fun BlueprintStep.copyTo(onboardingPhase: OnboardingPhase): CopiedNode<OnboardingStep> {
        val onboardingStep = OnboardingStep(
            phase = onboardingPhase,
            position = position,
            title = title,
            description = description,
            type = type,
            aiAssisted = aiAssisted,
            estimatedMinutes = estimatedMinutes,
            expectedOutcome = expectedOutcome,
            status = StepStatus.WAITING,
            graphX = graphX,
            graphY = graphY,
        )

        blueprintTasks
            .sortedBy { it.position }
            .map { it.copyTo(onboardingStep) }
            .forEach(onboardingStep.tasks::add)
        blueprintResources
            .map { it.copyTo(onboardingStep) }
            .forEach(onboardingStep.resources::add)

        return CopiedNode(id, onboardingStep)
    }

    private fun BlueprintCheckQuestion.copyTo(
        onboardingPhase: OnboardingPhase,
    ): CopiedNode<PhaseCheckQuestion> {
        val onboardingQuestion = PhaseCheckQuestion(
            phase = onboardingPhase,
            title = title,
            position = position,
            type = type,
            question = question,
            explanation = explanation,
            correctAnswer = correctAnswer,
            graphX = graphX,
            graphY = graphY,
        )

        blueprintCheckOptions
            .sortedBy { it.position }
            .map { it.copyTo(onboardingQuestion) }
            .forEach(onboardingQuestion.options::add)

        return CopiedNode(id, onboardingQuestion)
    }

    private fun BlueprintTask.copyTo(onboardingStep: OnboardingStep): OnboardingTask {
        return OnboardingTask(
            step = onboardingStep,
            position = position,
            title = title,
            description = description,
        )
    }

    private fun BlueprintResource.copyTo(onboardingStep: OnboardingStep): OnboardingResource {
        return OnboardingResource(
            step = onboardingStep,
            title = title,
            description = description,
            url = url,
        )
    }

    private fun BlueprintCheckOption.copyTo(onboardingQuestion: PhaseCheckQuestion): PhaseCheckOption {
        return PhaseCheckOption(
            question = onboardingQuestion,
            position = position,
            label = label,
            correct = correct,
        )
    }

    private data class CopiedPhase(
        val sourceBlueprintId: UUID,
        val entity: OnboardingPhase,
    )

    private data class CopiedNode<T : OnboardingSubGraphNode>(
        val sourceBlueprintId: UUID,
        val entity: T,
    )
}
