### List all Connectors

GET http://localhost:8080/api/v1/connectors HTTP/1.1

### Enable connector invalid id syntax

PATCH http://localhost:8080/api/v1/connectors/GITHUB HTTP/1.1
Content-Type: application/json

{
    "enabled": true
}

### Enable connector

PATCH http://localhost:8080/api/v1/connectors/github HTTP/1.1
Content-Type: application/json

{
    "enabled": true
}

### Disable connector

PATCH http://localhost:8080/api/v1/connectors/github HTTP/1.1
Content-Type: application/json

{
    "enabled": false
}

### Get all sources of github connector

GET http://localhost:8080/api/v1/connectors/github/sources HTTP/1.1
