-- The generation_status check constraint is generated by Hibernate (ddl-auto: update) from the
-- GenerationStatus enum and is baked with the enum values known when it was first created. Adding
-- TIMED_OUT to the enum does not update the constraint on existing databases, so TIMED_OUT rows
-- are rejected. Recreate it with the full value list. (Fresh databases already get the full list
-- from Hibernate.)
ALTER TABLE onboarding_phases
    DROP CONSTRAINT IF EXISTS onboarding_phases_generation_status_check;

ALTER TABLE onboarding_phases
    ADD CONSTRAINT onboarding_phases_generation_status_check
    CHECK (generation_status IN ('NOT_APPLICABLE', 'GENERATED', 'EMPTY', 'SKIPPED', 'FAILED', 'TIMED_OUT'));
